# Run configuration
inputdir:   "input"
fn_pattern: "{sample}_{readpair}_001.fastq.gz"
outputdir:  "output"
fastadir:   "output/fasta"
fastpdir:   "output/fastp"
fastqdir:   "output/fastq"
bamdir:     "output/bam"
countsdir:  "output/counts"
logdir:     "output/logs"
report:     "output/workflow-report-"

# Workflow steps
run_fastp:          True
run_fastp_dedup:    True
run_fastp_merge:    True
run_fastq_to_fasta: True
run_bwa_mem:        True
run_parse_bam:      True

# Extra options to tools
# fastp
fastp:
    extra: "--detect_adapter_for_pe --correction --cut_right "
    n: 4
    dup_calc_accuracy: 3
    length_required: 116

# fastq_to_fasta using seqtk seq
fastq_to_fasta:
    extra: ""
    n: 1

# tab_to_fasta using seqkit
tab_to_fasta:
    extra: "-t dna"
    n: 4

# bwa_index using bwa index
bwa_index:
    extra: ""
    n: 4

# bwa_mem using bwa mem
bwa_mem:
    extra: ""
    n: 4

# samtools_index using samtools index
samtools_index:
    extra: ""
    n: 4

# parse_bam using parse.py. m is mismatches, g is gene length
parse_bam:
    extra: ""
    n: 4
    m: 2
    g: 9

